version: '3.7'

volumes:
    logs:
        driver: local

services:
    pokemon-mlz:
        build: .
        image: pokemon-mlz
        container_name: pokemon-mlz
        working_dir: /usr/src/app
        ports:
            - 80:${FLASK_PORT}
            - ${APIDOC_PORT}:${APIDOC_PORT}
        tty: true
        volumes:
            - .:/usr/src/app